### ISSUE TITLE
ByteArray

### ISSUE THREAD

**Issue by Zaseth** [Turkitutu/cheesy.js#3]
Hi there.

I noticed that [my library](https://github.com/Zaseth/bytearray-node) is being used in your project. This is not done by 'Omaraldin'.

**Comment by Omaraldin** [comment]
> Hi there.
> 
> I noticed that [my library](https://github.com/Zaseth/bytearray-node) is being used in your project. This is not done by 'Omaraldin'.

Hi, `// Thanks to @Omaraldin` message doesn't mean that all codes in files are made by me something, if you take a look for the whole code you'll see somethings like `xorCipher`, `blockCipher` and `XXTEA` which i helped with.
Nothing said it's made by me, and we've used and edited only one file from your library and modified most of things.

And, we've added link for your library anyway, thanks and sorry for misunderstand.

**Comment by Zaseth** [comment]
I recommend using my library in NPM as I update it regularly.

**Comment by Omaraldin** [comment]
Your library is really good specially for people who were working with AS3, but we were just need tiny things such String, Int, Short, Byte and Bytes reading/writing other things like AMF3 is not useful for what our looking for, and we were working hurry to be sure that if we will make connection successfully or not, that's why we didn't make own system.
